name: Build "FEX"

on:
  workflow_dispatch:

jobs:
  start_building_fex:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3

    - name: Execute build script
      run: |
         bash ./arm64ec_fex_build.sh
         llvm-strip /usr/lib/wine/aarch64-windows/libarm64ecfex.dll
         llvm-strip /usr/lib/wine/aarch64-windows/libwow64fex.dll

    - name: Get current date
      id: date
      run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

    - name: Release "DXVK+FEX"
      uses: softprops/action-gh-release@v1
      with:
        body: DXVK+FEX BUILD
        tag_name: ${{ steps.date.outputs.DATE }}
        name: DXVK+FEX BUILD ${{ steps.date.outputs.DATE }}
        files: |
           /usr/lib/wine/aarch64-windows/libarm64ecfex.dll
           /usr/lib/wine/aarch64-windows/libwow64fex.dll
